import React from 'react';
import Avatar from "./Avatar";
import SceneLoader from "./SceneLoader";
import SceneRenderer from './SceneRenderer';

/**
 * WorldEngine, class to build the world, contains setup for the renderer and animator and pointers to scene items
 * @param container: the id of the container to insert the canvas element generated by the renderer
 * @constructor
 */
export default class WorldEngine extends React.Component {

    constructor() {

        super();

        this.animate = this.animate.bind(this);
        this.activateWorld = this.activateWorld.bind(this);
        this.state = {
            touch: false,
            running: false
        };

    }

    activateWorld(touchMode) {

        console.log("Activating world... touch mode? " + touchMode);

        this.setState({running: true, touch: touchMode});

        const container = document.getElementById("renderContainer");
        const {width, height} = container.getBoundingClientRect()
		const w = width * 0.25
		const h = height * 0.25
		// const w = width
		// const h = height
		const rat = w / h

        this.avatar = new Avatar(touchMode, rat);
        this.scene = new SceneLoader(this.avatar);
        this.renderer = new SceneRenderer(container, this.avatar, this.scene, w, h);
        this.previousTime = null;

        this.animate(performance.now());

    }

    componentWillUnmount() {

        this.scene.getActiveSceneObject().exitRoom();
        this.avatar.removeEvents();
        this.renderer.removeEvents();

    }

    getDelta(time) {

        this.previousTime = this.previousTime || time;
        let delta = (time - this.previousTime) * 0.001;
        this.previousTime = time;
        return delta;

    }

    animate(time) {

        requestAnimationFrame(this.animate);

        let delta = this.getDelta(time);

        this.avatar.update(delta);
        this.scene.update(delta);
        this.renderer.update();

    }

    render() {

        let viewer = (this.state.running) ?
            (this.state.touch) ?
                <div className="touchArrows">
                    <div className="forward">
                        <span id="forward">↑</span>
                    </div>
                    <div className="left">
                        <span id="left">←</span>
                    </div>
                    <div className="backward">
                        <span id="backward">↓</span>
                    </div>
                    <div className="right">
                        <span id="right">→</span>
                    </div>
                </div> :
                null
            :
            <div className="optionScreen">
                <p>Both of the following options will activate full-screen mode on compatible devices.</p>
                <div className="option1">
                    <p>To activate keyboard and mouse control devices, using WASD keys for movement and the mouse to look:</p>
                    <button onClick={() => this.activateWorld(false)}>Click here</button>
                </div>
                <div className="option2">
                    <p>To activate touch screen devices, using the on-screen buttons for movement and touch-dragging to look:</p>
                    <button onClick={() => this.activateWorld(true)}>Touch here</button>
                </div>
            </div>;

        return(

            <div className='container' id="renderContainer">

                { viewer }

            </div>

        );

    }

}